"""httpware — thin async + sync HTTP client wrapper over httpx2."""

from httpware.client import AsyncClient, Client
from httpware.decoders import ResponseDecoder
from httpware.errors import (
    STATUS_TO_EXCEPTION,
    BadRequestError,
    BulkheadFullError,
    CircuitOpenError,
    ClientError,
    ClientStatusError,
    ConflictError,
    DecodeError,
    ForbiddenError,
    InternalServerError,
    MissingDecoderError,
    NetworkError,
    NotFoundError,
    RateLimitedError,
    RetryBudgetExhaustedError,
    ServerStatusError,
    ServiceUnavailableError,
    StatusError,
    TimeoutError,  # noqa: A004
    TransportError,
    UnauthorizedError,
    UnprocessableEntityError,
)
from httpware.middleware import (
    AsyncMiddleware,
    AsyncNext,
    Middleware,
    Next,
    after_response,
    async_after_response,
    async_before_request,
    async_on_error,
    before_request,
    on_error,
)
from httpware.middleware.resilience import (
    AsyncBulkhead,
    AsyncCircuitBreaker,
    AsyncRetry,
    AsyncTimeout,
    Bulkhead,
    Retry,
    RetryBudget,
)


__all__ = [
    "STATUS_TO_EXCEPTION",
    "AsyncBulkhead",
    "AsyncCircuitBreaker",
    "AsyncClient",
    "AsyncMiddleware",
    "AsyncNext",
    "AsyncRetry",
    "AsyncTimeout",
    "BadRequestError",
    "Bulkhead",
    "BulkheadFullError",
    "CircuitOpenError",
    "Client",
    "ClientError",
    "ClientStatusError",
    "ConflictError",
    "DecodeError",
    "ForbiddenError",
    "InternalServerError",
    "Middleware",
    "MissingDecoderError",
    "NetworkError",
    "Next",
    "NotFoundError",
    "RateLimitedError",
    "ResponseDecoder",
    "Retry",
    "RetryBudget",
    "RetryBudgetExhaustedError",
    "ServerStatusError",
    "ServiceUnavailableError",
    "StatusError",
    "TimeoutError",
    "TransportError",
    "UnauthorizedError",
    "UnprocessableEntityError",
    "after_response",
    "async_after_response",
    "async_before_request",
    "async_on_error",
    "before_request",
    "on_error",
]
